config/routes.rb
Rails.application.routes.draw do
  resources :books
	#get "new", to: "articles#new" 

	resources :articles do 
		resources :comments
		get 'preview', on: :member
		get 'search', on: :collection
	end
	root "articles#index"

	#get "/articles", to: "articles#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	#attr_accessible :title, :body
	has_many :comments, dependent: :destroy

	validates :title, :body , :presence => true
	validates :title, :length => { :minimum => 5}
	validates :title, :uniqueness => { :message => "already taken" }
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true
  #before_validation :ensure_comment_has_a_value
  
  

  private
    def ensure_comment_has_a_value
      if self.body.present?
        self.body = "Noted Comment without body by #{self.commenter}"
      end
    end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
	before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
  	@articles = Article.all.order("created_at DESC")
  end

  def new
  	@article = Article.new 
  end

  def create
  	@article = Article.new(article_params)
  	if @article.save
  		redirect_to @article
  	else
  		render 'new'
  	end
  end

  def show
  	# debugger
  	#render :show, layout: false
  end

  def edit
  end

  def preview
  	debugger
  end

  def search
  	debugger
  end

  def update
  	if  @article.update(article_params)
  		redirect_to @article
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@article.destroy
  	redirect_to root_path
  end

  private 

  def find_article
  	@article = Article.find(params[:id])
  end

  def article_params
  	params.require(:article).permit(:title, :body)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def create
		@article = Article.find(params[:article_id])
    	@comment = @article.comments.create(comment_params)
    	redirect_to article_path(@article)
		
	end

	def destroy
		@article = Article.find(params[:article_id])
    	@comment = @article.comments.find(params[:id])
    	@comment.destroy
    	redirect_to article_path(@article)
	end

	private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def render_button
		content_tag(:div) do
			content_tag(:button, "Click me", :onclick => "alert('Hello From Helper!!')")
		end
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_abc.html.erb
<h2>Rendered Partial View</h2>

<%= form_for @article do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br> 
	<%= f.submit %>
<% end %> 

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<%	if @article.errors.any? %>
	<h2>Errors:</h2>
	<ul>
		<% @article.errors.full_messages.each do |message| %>
			<li><%= message %></li> 
			<% end %>
	</ul>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br> 
	<%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<!-- <ul>
	<%	@articles.each do |article| %>
	<li>
		<%= article.title %>
	</li>
	<% end %>
</ul> -->

<% @articles.each do |article| %>
<h2><%= article.title %></h2>
<div><%= truncate(article.body, :length => 35) %>
</div>
<br>
<%= link_to "Read Article", article %>
<% end %>

<hr>
<%= render_button %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div>
	<%= @article.body %>
</div> 
<br>
<%= link_to "Edit Article", edit_article_path(@article) %>
<%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: "Are your sure?"} %>

<h2> <%= @article.comments.count %> Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
  	<%= link_to 'Delete Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
  </p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!-- <body style="background-image: url(<%= asset_url('img.jpg') %>);"> -->
  <body>
    <!-- <br>
    <%= image_tag "img.jpg" %> -->
    <br>
    <%= link_to "Home", root_path %>
    <%= link_to "New Article", new_article_path %>
    <%= yield %>
  </body>
</html>

app/views/layouts/new_layout.html.erb
new_layout.html.erb